//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Equipment
    {
        public string Booking_Equipment_ID { get; set; }
        public string User_ID { get; set; }
        public string Equipment_ID { get; set; }
        public Nullable<System.DateTime> Booking_Equipment_DateTime_Start { get; set; }
        public Nullable<System.DateTime> Booking_Equipment_DateTime_End { get; set; }
        public string Booking_Equipment_Purpose { get; set; }
        public Nullable<int> Equipment_Num { get; set; }
        public int ID { get; set; }
    }
}
