//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public string Equipment_ID { get; set; }
        public string Equipment_Name { get; set; }
        public string Equipment_Brand { get; set; }
        public string Equipment_Series { get; set; }
        public string Equipment_Status { get; set; }
        public Nullable<int> Equipment_Num { get; set; }
        public int ID { get; set; }
    }
}
