//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public string Payment_ID { get; set; }
        public string Booking_ID { get; set; }
        public string Payment_Chanace { get; set; }
        public Nullable<decimal> Payment_Price { get; set; }
        public string Payment_Status { get; set; }
        public int ID { get; set; }
    }
}
