//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Status
    {
        public string Satatus_ID { get; set; }
        public string Room_ID { get; set; }
        public Nullable<System.DateTime> Booking_DataTime { get; set; }
        public string Satatus_Name { get; set; }
        public int ID { get; set; }
    }
}
