//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookin1
{
    using System;
    using System.Collections.Generic;
    
    public partial class signup
    {
        public string User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Lastname { get; set; }
        public string User_Tel { get; set; }
        public Nullable<System.DateTime> User_Brithday { get; set; }
        public string User_Email { get; set; }
        public string User_Username { get; set; }
        public string User_Password { get; set; }
        public int ID { get; set; }
    }
}
